/*\n  # Update Storm Risk Calculation Function\n\n  ## Overview\n  This migration updates the calculate_storm_risk function to properly convert 1-5 scale scores to 0-100 scale.\n\n  ## Changes\n  \n  ### Updated Calculation Formula\n  - StormRiskScore = (hurricane * 0.50 + flood * 0.30 + insurance * 0.20) * 20\n  - Wind Exposure = hurricane_risk_score * 20\n  - Flood Exposure = flood_risk_score * 20\n  - Coastal Exposure = coastal_exposure_score * 20\n  \n  ### Updated Risk Level Thresholds\n  - 0-39: Low\n  - 40-59: Moderate\n  - 60-79: High\n  - 80-100: Critical\n  \n  ## Database Schema Update\n  \n  The function now expects scores on a 1-5 scale and converts them to 0-100 for display.\n*/\n\n-- Drop the existing function\nDROP FUNCTION IF EXISTS calculate_storm_risk(text);
\n\n-- Create updated function with correct calculation\nCREATE OR REPLACE FUNCTION calculate_storm_risk(zip_input text)\nRETURNS json\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nDECLARE\n  result json;
\n  risk_record RECORD;
\n  risk_level text;
\n  calculated_score integer;
\n  insurance_numeric integer;
\nBEGIN\n  -- Try to find the ZIP in the database\n  SELECT \n    zip_code,\n    hurricane_risk_score,\n    flood_risk_score,\n    coastal_exposure_score,\n    insurance_claim_risk\n  INTO risk_record\n  FROM zip_risk_map\n  WHERE zip_code = zip_input;
\n  \n  -- If ZIP found, use actual data\n  IF FOUND THEN\n    -- Convert insurance_claim_risk text to numeric (1-5 scale)\n    CASE risk_record.insurance_claim_risk\n      WHEN 'Low' THEN insurance_numeric := 1;
\n      WHEN 'Moderate' THEN insurance_numeric := 3;
\n      WHEN 'High' THEN insurance_numeric := 4;
\n      WHEN 'Severe' THEN insurance_numeric := 5;
\n      WHEN 'Critical' THEN insurance_numeric := 5;
\n      ELSE insurance_numeric := 3;
\n    END CASE;
\n    \n    -- Calculate weighted score and convert to 0-100 scale\n    -- Formula: (hurricane * 0.50 + flood * 0.30 + insurance * 0.20) * 20\n    calculated_score := ROUND(\n      (risk_record.hurricane_risk_score * 0.50 + \n       risk_record.flood_risk_score * 0.30 + \n       insurance_numeric * 0.20) * 20\n    );
\n    \n    -- Determine risk level based on calculated score\n    IF calculated_score >= 80 THEN\n      risk_level := 'Critical';
\n    ELSIF calculated_score >= 60 THEN\n      risk_level := 'High';
\n    ELSIF calculated_score >= 40 THEN\n      risk_level := 'Moderate';
\n    ELSE\n      risk_level := 'Low';
\n    END IF;
\n    \n    -- Build response with converted scores (multiply by 20 to get 0-100 scale)\n    result := json_build_object(\n      'zip', risk_record.zip_code,\n      'score', calculated_score,\n      'risk_level', risk_level,\n      'hurricane_risk', risk_record.hurricane_risk_score * 20,\n      'flood_risk', risk_record.flood_risk_score * 20,\n      'coastal_exposure', risk_record.coastal_exposure_score * 20,\n      'insurance_risk', risk_record.insurance_claim_risk\n    );
\n  ELSE\n    -- ZIP not found, return fallback moderate risk (2.5 on 1-5 scale)\n    -- Calculated score: (2.5 * 0.5 + 2.5 * 0.3 + 3 * 0.2) * 20 = 52\n    result := json_build_object(\n      'zip', zip_input,\n      'score', 52,\n      'risk_level', 'Moderate',\n      'hurricane_risk', 50,\n      'flood_risk', 50,\n      'coastal_exposure', 50,\n      'insurance_risk', 'Moderate'\n    );
\n  END IF;
\n  \n  RETURN result;
\nEND;
\n$$;
\n\n-- Grant execute permission to anonymous and authenticated users\nGRANT EXECUTE ON FUNCTION calculate_storm_risk(text) TO anon, authenticated;
;
