/*\n  # Update get_storm_report function to include coordinates\n\n  1. Changes\n    - Modify get_storm_report function to return lat/lon coordinates\n    - Add latitude and longitude to the JSON response\n  \n  2. Security\n    - No security changes, function maintains existing access patterns\n*/\n\nCREATE OR REPLACE FUNCTION public.get_storm_report(input_zip text)\nRETURNS json\nLANGUAGE plpgsql\nAS $function$\ndeclare\n    v_score numeric;
\n    v_level text;
\n    v_components json;
\n    v_video text;
\n    v_hero text;
\n    v_recommendation text;
\n    v_lat numeric;
\n    v_lon numeric;
\nbegin\n\n    select\n        overall_risk_score,\n        lat,\n        lon,\n        json_build_object(\n            'hurricane_risk', hurricane_risk_score,\n            'flood_risk', flood_risk_score,\n            'coastal_exposure', coastal_exposure_score,\n            'distance_to_coast', distance_to_coast_score,\n            'fema_flood_zone', fema_flood_zone_score,\n            'hurricane_corridor', hurricane_corridor_score\n        )\n    into v_score, v_lat, v_lon, v_components\n    from florida_zip_reference\n    where zip_code = input_zip\n    limit 1;
\n\n    if v_score is null then\n        return json_build_object(\n            'error','ZIP code not found'\n        );
\n    end if;
\n\n    if v_score >= 80 then\n        v_level := 'HIGH';
\n        v_video := '/videos/storm-high.mp4';
\n        v_hero := '/images/storm-report-hero.png';
\n        v_recommendation := 'A professional storm readiness inspection is strongly recommended to identify potential vulnerabilities before the next storm season.';
\n        \n    elsif v_score >= 55 then\n        v_level := 'MODERATE';
\n        v_video := '/videos/storm-moderate.mp4';
\n        v_hero := '/images/storm-report-hero.png';
\n        v_recommendation := 'Your property has moderate storm exposure. An inspection can help confirm structural resilience and insurance readiness.';
\n        \n    else\n        v_level := 'LOW';
\n        v_video := '/videos/storm-low.mp4';
\n        v_hero := '/images/storm-report-hero.png';
\n        v_recommendation := 'Your area has lower storm exposure, but periodic inspections help maintain documentation and preparedness.';
\n    end if;
\n\n    return json_build_object(\n        'zip_code', input_zip,\n        'storm_risk_score', round(v_score),\n        'risk_level', v_level,\n        'hero_image', v_hero,\n        'video', v_video,\n        'risk_components', v_components,\n        'inspection_recommendation', v_recommendation,\n        'lat', v_lat,\n        'lon', v_lon\n    );
\n\nend;
\n$function$;
;
